1-Numpy kütüphanesini import edin.

In [51]:
import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [52]:
b = np.arange(6)
print(b)

[0 1 2 3 4 5]


3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [53]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [54]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

5- 10–70 e kadar 5 er artan sayıları yaz.

In [55]:
np.arange(10,71, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [56]:
np.linspace(10,20,15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [57]:
np.random.randint(low=0, high=100, size=(3,5)) #integers

array([[39, 21, 10, 73, 54],
       [ 2, 66, 57, 36, 79],
       [98, 70, 58, 47, 68]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [59]:
np.arange(0,24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [60]:
arr2 = np.random.uniform(low=0, high=1, size=10)
print(arr2, "\n")
print("max: ", arr2.max(), "\n") #max
print("min: ", arr2.min()) #min

[0.30834864 0.5485968  0.60462225 0.93793296 0.44863754 0.23233783
 0.67109714 0.27449201 0.406736   0.80335573] 

max:  0.9379329595436385 

min:  0.2323378286767711


11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [61]:
arr3 = np.random.rand(6,6)
print(arr3)

[[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651]
 [0.75619356 0.57523554 0.98092527 0.07363925 0.64430824 0.20279833]
 [0.72147463 0.083534   0.12019112 0.97491804 0.47708982 0.04141029]
 [0.41053535 0.09619655 0.15208199 0.40027241 0.68323641 0.78844373]
 [0.55612043 0.4013695  0.82930282 0.54275168 0.45476353 0.03507585]
 [0.33348886 0.26909839 0.56822222 0.46142026 0.47665171 0.21356222]]


12- 5.satırdaki elemanları gösteriniz.

In [62]:
arr3[4]

array([0.55612043, 0.4013695 , 0.82930282, 0.54275168, 0.45476353,
       0.03507585])

13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [63]:
arr3[5,5]

0.21356221596834035

14-4.sutundaki tüm elemanları çekin.

In [64]:
arr3[:,5]

array([0.77435651, 0.20279833, 0.04141029, 0.78844373, 0.03507585,
       0.21356222])

15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [65]:
for i in range(np.size(arr3)):
    print(arr3.flat[0:i])

[]
[0.45194515]
[0.45194515 0.45307513]
[0.45194515 0.45307513 0.74869493]
[0.45194515 0.45307513 0.74869493 0.28045289]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712 ]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651
 0.75619356]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651
 0.75619356 0.57523554]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651
 0.75619356 0.57523554 0.98092527]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651
 0.75619356 0.57523554 0.98092527 0.07363925]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651
 0.75619356 0.57523554 0.98092527 0.07363925 0.64430824]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651
 0.75619356 0.57523554 0.98092527 0.07363925 0.64430824 0.20279833]
[0.45194515 0.45307513 0.74869493 0.28045289 0.7954712  0.77435651
 0.75619356 0.57523554 0.98092527 0.073639

16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [66]:
arr4 = np.arange(0,1, 0.1).reshape(2,5)
print(arr4)
arr4 *=5
print(arr4)

[[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]]
[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]]


17- Satırların toplam değeri nedir?

In [67]:
arr4.sum()

22.5

18-Satırların standart sapma değeri nedir?

In [68]:
arr4.std()

1.4361406616345072

19-Satırların varyans değeri nedir?

In [69]:
arr4.var()

2.0625

20- Satırların transpoz değeri nedir?

In [70]:
arr4.transpose()

array([[0. , 2.5],
       [0.5, 3. ],
       [1. , 3.5],
       [1.5, 4. ],
       [2. , 4.5]])